#!/usr/bin/env bash

# Make sure needed commands exhist.
command_exists() {
    [[ -n "$1" ]] && type "$1" >/dev/null 2>&1
}

function ffonts() {

    local fonts FZF_OPTS

    FZF_OPTS=(
        --cycle
        --reverse
        --border
        --pointer=
        --prompt=Search:
        --bind shift-up:preview-page-up
        --bind shift-down:preview-page-down
        --bind ctrl-c:abort
        --bind ctrl-q:abort
        --bind esc:abort)

    #fc-list -f '%{file}\n' | /usr/bin/fzf "${FZF_OPTS[@]}"
    #fc-list | sort | /usr/bin/fzf "${FZF_OPTS[@]}"
    fc-match -a 'Monospace' | sort | uniq | /usr/bin/fzf "${FZF_OPTS[@]}"
}

# simple extract command.
#TODO: finish separate fzf-extract standalone script and remove this.
ex() {
    if [ -f "$1" ]; then
        case "$1" in
        *.tar.bz2) tar xjf "$1" ;;
        *.tar.gz) tar xzf "$1" ;;
        *.tar.xz) tar xf "$1" ;;
        *.tar.zst) tar xf "$1" ;;
        *.tar) tar xf "$1" ;;
        *.bz2) bunzip2 "$1" ;;
        *.rar) unrar x "$1" ;;
        *.gz) gunzip "$1" ;;
        *.tbz2) tar xjf "$1" ;;
        *.tgz) tar xzf "$1" ;;
        *.zip) unzip "$1" ;;
        *.Z) uncompress "$1" ;;
        *.7z) 7z x "$1" ;;
        *.deb) ar x "$1" ;;
        *) echo "$1 cannot be extracted via ex()" ;;
        esac
    else
        echo "$1 is not a valid file"
    fi
}

# remove icons from exa --icons cmd
function strip_icons {
    rev |
        cut -f1 -d' ' |
        rev |
        sed \
            -e 's/\[[0-9];[0-9][0-9]m//g' \
            -e 's/\[[0-9];[0-9];[0-9][0-9]m//g' \
            -e 's/\[0m//g' \
            -e 's/\[1m//g' \
            -e 's///g'
}

## CHATGPT FIXED VERSION:::
#function strip_icons {
#    sed -E -e 's/\x1B\[[0-9;]*[mGK]//g' -e 's/\x0E//g' -e 's/\x0F//g'
#}

# ----------------- colors
## Description :
## Easy to use, simple color wrappers for the echo/tput commands.

#BOLD="$(tput bold)"
#UNDERLINE="$(tput sgr 0 1)"
#BLINK="$(tput blink)"
#INVERT="$(tput sgr 1 0)"

## Color Functions
red() {
    local RED NORMAL
    RED="$(tput setaf 1)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${RED}$1${NORMAL}"
}
green() {
    local GREEN NORMAL
    GREEN="$(tput setaf 2)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${GREEN}$1${NORMAL}"
}
yellow() {
    local YELLOW NORMAL
    YELLOW="$(tput setaf 3)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${YELLOW}$1${NORMAL}"
}
blue() {
    local BLUE NORMAL
    BLUE="$(tput setaf 4)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${BLUE}$1${NORMAL}"
}
magenta() {
    local MAGENTA NORMAL
    MAGENTA="$(tput setaf 5)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${MAGENTA}$1${NORMAL}"
}
cyan() {
    local CYAN NORMAL
    CYAN="$(tput setaf 6)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${CYAN}$1${NORMAL}"
}
white() {
    local WHITE NORMAL
    WHITE="$(tput setaf 7)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${WHITE}$1${NORMAL}"
}
grey() {
    local GREY NORMAL
    GREY="$(tput setaf 8)"
    NORMAL="$(tput sgr0)"
    builtin echo -e "${GREY}$1${NORMAL}"
}
