#!/usr/bin/env bash

# DO NOT EDIT THIS FILE. USE DROP IN DIRS AND FILES IN "$HOME/.config/shell/**"

bashrc="${HOME}/.config/shell/bashrc"
if test -f "${bashrc}" ; then
	if test -r "${bashrc}" ; then
		source "${bashrc}"
	else
		echo "Could't read: ${bashrc}"
	fi
else
	echo "File doesn't exhist: ${bashrc}"
fi
unset bashrc
