#!/usr/bin/env bash

# $HOME/.bash_profile

# DO NOT EDIT THIS FILE. USE DROP IN DIRS IN
# $HOME/.config/shell/**

bashrc="$HOME/.config/shell/bash/bashrc"
if test -f "$bashrc" ; then
	if test -r "$bashrc" ; then
		source "$bashrc"
	else
		echo "Could't read: $bashrc"
	fi
else
	echo "File doesn't exhist: $bashrc"
fi
unset bashrc
