#!/usr/bin/env bash

# Shared env variables for shell.

## ----------------- xdg

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}

## ----------------- dotnet

export DOTNET_CLI_TELEMETRY_OPTOUT=1

## ----------------- fix-paths

# Use tool xdg-ninja to detect unwanted files/dirs in $HOME that can be moved to XDG dirs.

# rust
export CARGO_HOME="${CARGO_HOME:-$XDG_DATA_HOME/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$XDG_DATA_HOME/rustup}"

# golang
#export GOPATH=
#export GOBIN=
#export GOCACHE=

# python
export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"

# node
export NODE_OPTIONS="--max-old-space-size=4096" # --openssl-legacy-provider"
export NPM_CONFIG_USERCONFIG="${NPM_CONFIG_USERCONFIG:-$XDG_CONFIG_HOME/npm/npmrc}"
export NODE_REPL_HISTORY="${NODE_REPL_HISTORY:-$XDG_DATA_HOME/nodejs/repl_history}"

# volta
export VOLTA_HOME="$HOME/.volta"

# npm
#export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
#export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
#export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# gpg
export GNUPGHOME="${GNUPGHOME:-$XDG_DATA_HOME/gnupg}"

# ccache
export CCACHE_CONFIGPATH=$XDG_CONFIG_HOME/ccache.config
export CCACHE_DIR=$XDG_CACHE_HOME/ccache

# android
export ANDROID_SDK_HOME=$XDG_CONFIG_HOME/android
export ANDROID_SDK_ROOT=$XDG_DATA_HOME/android
export ANDROID_AVD_HOME=$XDG_DATA_HOME/android
export ANDROID_EMULATOR_HOME=$XDG_DATA_HOME/android
export ADB_VENDOR_KEY=$XDG_CONFIG_HOME/android

# postgres
export PSQLRC="${PSQLRC:-$XDG_CONFIG_HOME/pg/psqlrc}"
export PSQL_HISTORY="${PSQL_HISTORY:-$XDG_CACHE_HOME/pg/psql_history}"
export PGPASSFILE="${PGPASSFILE:-$XDG_CONFIG_HOME/pg/pgpass}"
export PGSERVICEFILE="${PGSERVICEFILE:-$XDG_CONFIG_HOME/pg/pg_service.conf}"

# mix
export WGETRC="${WGETRC:-$XDG_CONFIG_HOME/wget/wgetrc}"
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export JUPYTER_CONFIG_DIR="${JUPYTER_CONFIG_DIR:-$XDG_CONFIG_HOME/jupyter}"
export VAGRANT_HOME="$XDG_DATA_HOME"/vagrant
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority

# export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

## ----------------- default-programs

export LANGUAGE=en_US
export BROWSER="/usr/bin/firefox"
#export BROWSER="/usr/bin/brave"

export EDITOR="/usr/bin/micro"
#export EDITOR="/usr/bin/emacsclient -t -a ''"
export ALTERNATE_EDITOR="/usr/bin/emacsclient -t -a ''"
export VISUAL="/usr/bin/vscodium"
export TERMINAL="/usr/bin/alacritty"
export READER="/usr/bin/zathura"
export VIDEO="/usr/bin/mpv"
export IMAGE="/usr/bin/sxic"
export OPENER="/usr/bin/xdg-open"
#export PAGER=""
export COLORTERM="truecolor"
# Bat as manpager
export MANPAGER="/usr/bin/batman"
#export MANPAGER="/bin/sh -c 'col -bx | bat -l man -p'"

## ----------------- starship

# export STARSHIP_CONFIG=~/.config/starship/starship.toml
# export STARSHIP_CACHE=~/.cache/starship/session_$(STARSHIP_SESSION_KEY).log

## ----------------- random

# git
export GIT_CONFIG_NOSYSTEM="true"
export GIT_CONFIG_NOGLOBAL="true"

# Micro Editor
export MICRO_TRUECOLOR=1

# exa
export EXA_STRICT=1

# systemd
export SYSTEMD_LESSCHARSET="utf-8"
export SYSTEMD_PAGERSECURE="1"
export SYSTEMD_COLORS="256"
export SYSTEMD_URLIFY="1"
export SYSTEMD_EDITOR="/usr/bin/micro"
export SYSTEMD_LOG_COLOR="1"

## -----------------
