#!/usr/bin/env bash

# If not running interactively, don't do anything.
case $- in
    *i*) ;;
      *) return;;
esac

HISTSIZE=999999999
HISTFILESIZE=999999999
HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s histverify
shopt -s checkwinsize
shopt -s globstar
shopt -s extglob

[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases




