#!/usr/bin/env bash

# $HOME/.config/shell/bash/bashenv

# Use this file for all bash env

## ----------------- shared-environment

# Source shared env vars
sauce "$SHARED/envrc"

## ----------------- bash-env

# Bash specific env vars.

HISTTIMEFORMAT='%F %T '   # use standard ISO 8601 timestamp

HISTFILE=${XDG_DATA_HOME:-$HOME/.local/state}/bash/history

HISTSIZE=20000
HISTFILESIZE=${HISTSIZE}

HISTCONTROL=ignoreboth:erasedups
HISTIGNORE="ls:exa:cl:cd:top:exit:date"

## -----------------
