#!/usr/bin/env zsh

# $HOME/.zshrc

# DO NOT EDIT THIS FILE. USE DROP IN DIRS IN $XDG_CONFIG_HOME/shell/zsh/*.d

zshrc="$HOME/.config/shell/zsh/zshrc"
if test -f "$zshrc" ; then
	if test -r "$zshrc" ; then
		source "$zshrc"
	else
		echo "Could't read: $zshrc"
	fi
else
	echo "File doesn't exhist: $zshrc"
fi
unset zshrc
