#!/usr/bin/env bash
#
# SG
#

# $XDG_CONFIG_HOME/direnv/direnvrc

## -----------------  -----------------  -----------------  -----------------  -----------------

# Usage: use_env_dir [env_dir]
#
# Load environment variables from `$(direnv_layout_dir)/envs" directory.
# Under this directory, every file is read and set to an environment
# variable whose name is the filename and value is the file content.
#
# Also watch files so to automatially reload on every file update.

# https://github.com/direnv/direnv/wiki/Direnv-env-dir

# Add "use_env_dir /path/to/envdir" to per project .envrc to use.

use_env_dir() {
  local env_dir
  env_dir="${1:-$(direnv_layout_dir)/envs}"
  if [[ -d $env_dir ]]; then
    for f in "$env_dir"/*; do
      if [[ -f $f ]]; then
        watch_file "$f"
        export "$(basename "$f")=$(cat "$f")"
      fi
    done
  fi
}

## -----------------  -----------------  -----------------  -----------------  -----------------
